import pandas as pd
import mysql.connector
import boto3
from botocore.exceptions import NoCredentialsError

# MySQL connection parameters
db_config = {
    "host": "hostname",
    "user": "user_name",
    "password": "password",
    "database": "database_name",
}

# Establish MySQL connection
connection = mysql.connector.connect(**db_config)

# Query data and save to CSV
sql_query = "SELECT * FROM Demo_table"
df = pd.read_sql(sql_query, connection)
output_csv_path = "/home/vivek/Desktop/my_projects/output.csv"
df.to_csv(output_csv_path, index=False)

# Close the connection
connection.close()

# Upload CSV to S3
s3_bucket_name = "bucket_name"
s3_key = "output.csv"
aws_access_key = "XXXXXXXXXXXXXXXXXXX"
aws_secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

def upload_to_s3(bucket, key, local_file_path):
    s3 = boto3.client("s3", aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key)
    try:
        s3.upload_file(local_file_path, bucket, key)
        print("Upload Successful")
    except NoCredentialsError:
        print("Credentials not available")

upload_to_s3(s3_bucket_name, s3_key, output_csv_path)
